=== Nick-LCY/DND_core/schemas/feature.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "properties": {
        "name": {
            "$ref": "internal/i18nKey.json",
            "description": "特性名字"
        },
        "description": {
            "$ref": "internal/i18nKey.json",
            "description": "特性详情"
        },
        "category": {
            "title": "特性分类",
            "description": "目前有：race_traits, race_proficiencies, subrace_traits, subrace_proficiencies",
            "enum": [
                "race_traits",
                "race_proficiencies",
                "subrace_proficiencies",
                "subrace_traits"
            ]
        },
        "effects": {
            "title": "效果列表",
            "description": "与此特性有关的效果",
            "anyOf": [
                {
                    "$ref": "internal/effectDict.json"
                },
                {
                    "type": "array",
                    "items": {
                        "anyOf": [
                            {
                                "$ref": "internal/effectDict.json"
                            },
                            {
                                "$ref": "internal/id.json",
                                "title": "效果id，推荐先看看目前已有的分类"
                            }
                        ]
                    }
                }
            ]
        }
    },
    "required": [
        "name",
        "description",
        "category",
        "effects"
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/features/elf/wood/weapons.json
{"name": "%features.elf.wood.weapons/name%", "description": "%features.elf.wood.weapons/description%", "category": "subrace_proficiencies", "effects": ["_dnd5e:effects.proficiencies.weapons.longsword", "_dnd5e:effects.proficiencies.weapons.shortsword", "_dnd5e:effects.proficiencies.weapons.shortbow", "_dnd5e:effects.proficiencies.weapons.longbow"]}

=== Nick-LCY/DND_core/data/_dnd5e/features/gnome/cunning.json
{
    "name": "%features.gnome.cunning/name%",
    "description": "%features.gnome.cunning/description%",
    "category": "race_traits",
    "effects":[
        "_dnd5e:effects.advantages.saves.int_against_magic",
        "_dnd5e:effects.advantages.saves.wis_against_magic",
        "_dnd5e:effects.advantages.saves.cha_against_magic"
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/features/human/abilities.json
{
    "name": "",
    "description": "",
    "category": "race_traits",
    "effects": [
        "_dnd5e:effects.abilities.str_add@1",
        "_dnd5e:effects.abilities.dex_add@1",
        "_dnd5e:effects.abilities.con_add@1",
        "_dnd5e:effects.abilities.int_add@1",
        "_dnd5e:effects.abilities.wis_add@1",
        "_dnd5e:effects.abilities.cha_add@1"
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/features/dragonborn/resists.json
{"name": "%features.dragonborn.resists/name%", "description": "%features.dragonborn.resists/description%", "category": "race_traits", "effects": [{"choose": 1, "available": ["effects.resists.acid", "effects.resists.cold", "effects.resists.fire", "effects.resists.lightning", "effects.resists.poison"]}]}

=== Nick-LCY/DND_core/data/_dnd5e/features/elf/high/weapons.json
{"name": "%features.elf.high.weapons/name%", "description": "%features.elf.high.weapons/description%", "category": "subrace_proficiencies", "effects": ["_dnd5e:effects.proficiencies.weapons.longsword", "_dnd5e:effects.proficiencies.weapons.shortsword", "_dnd5e:effects.proficiencies.weapons.shortbow", "_dnd5e:effects.proficiencies.weapons.longbow"]}

=== Nick-LCY/DND_core/data/_dnd5e/features/high_elf/elf_weapon_training.json
{
    "name": "精灵武器训练",
    "description": "你拥有长剑、短剑、短弓和长弓的熟练项。",
    "category": "subrace_traits",
    "effects": [
        {"type": "permanent", "effect": "_dnd5e:effects.longsword_proficiency"},
        {"type": "permanent", "effect": "_dnd5e:effects.shortsword_proficiency"},
        {"type": "permanent", "effect": "_dnd5e:effects.shortbow_proficiency"},
        {"type": "permanent", "effect": "_dnd5e:effects.longbow_proficiency"}
    ]
}
