=== Nick-LCY/DND_core/schemas/spell_list_effect.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "法表效果",
    "description": "用于描述对法表产生影响的效果",
    "properties": {
        "type": {
            "type": "string",
            "enum": [
                "spell_list_effect"
            ]
        },
        "name": {
            "$ref": "internal/i18nKey.json",
            "title": "法表名字"
        },
        "description": {
            "$ref": "internal/i18nKey.json",
            "title": "法表详情"
        },
        "spells": {
            "title": "法表细节",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "known": {
                        "title": "限制从from的所有法术中选择多少个，如果为空则代表全选",
                        "type": "integer"
                    },
                    "from": {
                        "title": "可选的法术，内容可以是spell_list也可以是单个法术，最后会展开成要给单层的列表",
                        "anyOf": [
                            {
                                "$ref": "internal/id.json"
                            },
                            {
                                "type": "array",
                                "items": {
                                    "$ref": "internal/id.json"
                                }
                            }
                        ]
                    },
                    "start_level": {
                        "title": "从几级开始应用此法表与可学习法术，不能同时与level一起出现",
                        "type": "integer"
                    },
                    "end_level": {
                        "title": "从几级开始结束应用此法表与可学习法术，如果填start_level，不填这个则认为从start_level之后永远应用此效果",
                        "type": "integer"
                    },
                    "level": {
                        "title": "在第几级应用此法表，下一级就结束应用，不能与start_level一起出现",
                        "type": "integer"
                    },
                    "cantrip_only": {
                        "type": "boolean",
                        "title": "是否只包含戏法？默认为false"
                    },
                    "spell_only": {
                        "type": "boolean",
                        "title": "是否只包含法术？（即1级以上法术）默认为false"
                    }
                },
                "required": [
                    "from"
                ]
            }
        }
    },
    "required": [
        "name",
        "description",
        "spells",
        "type"
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/spell_list_effects/fighter/eldritch_knight_wizard_spells.json
{
    "name": "",
    "description": "",
    "type": "spell_list_effect",
    "spells": [
        {
            "from": "_dnd5e:spell_lists.wizard",
            "known": 1,
            "start_level": 3,
            "end_level": 8,
            "spell_only": true
        },
        {
            "from": "_dnd5e:spell_lists.wizard",
            "known": 2,
            "start_level": 8,
            "end_level": 14,
            "spell_only": true
        },
        {
            "from": "_dnd5e:spell_lists.wizard",
            "known": 3,
            "start_level": 14,
            "end_level": 20,
            "spell_only": true
        },
        {
            "from": "_dnd5e:spell_lists.wizard",
            "known": 4,
            "level": 20,
            "spell_only": true
        }
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/spell_list_effects/bard.json
{
    "type": "spell_list_effect",
    "name": "",
    "description": "",
    "spells": [
        {"level": 1, "known": 4, "from": "_dnd5e:spell_lists.bard"},
        {"level": 2, "known": 5, "from": "_dnd5e:spell_lists.bard"},
        {"level": 3, "known": 6, "from": "_dnd5e:spell_lists.bard"},
        {"level": 4, "known": 7, "from": "_dnd5e:spell_lists.bard"},
        {"level": 5, "known": 8, "from": "_dnd5e:spell_lists.bard"},
        {"level": 6, "known": 9, "from": "_dnd5e:spell_lists.bard"},
        {"level": 7, "known": 8, "from": "_dnd5e:spell_lists.bard"},
        {"level": 8, "known": 9, "from": "_dnd5e:spell_lists.bard"},
        {"level": 9, "known": 10, "from": "_dnd5e:spell_lists.bard"},
        {"level": 10, "known": 12, "from": "_dnd5e:spell_lists.bard"},
        {"level": 11, "known": 13, "from": "_dnd5e:spell_lists.bard"},
        {"level": 12, "known": 13, "from": "_dnd5e:spell_lists.bard"},
        {"level": 13, "known": 14, "from": "_dnd5e:spell_lists.bard"},
        {"level": 14, "known": 14, "from": "_dnd5e:spell_lists.bard"},
        {"level": 15, "known": 15, "from": "_dnd5e:spell_lists.bard"},
        {"level": 16, "known": 15, "from": "_dnd5e:spell_lists.bard"},
        {"level": 17, "known": 16, "from": "_dnd5e:spell_lists.bard"},
        {"start_level": 18, "known": 16, "from": "_dnd5e:spell_lists.bard"}
    ]
}

=== Nick-LCY/DND_core/data/_dnd5e/spell_list_effects/warlock/cantrips.json
{
    "name": "",
    "description": "",
    "type": "spell_list_effect",
    "spells": [
        {"known": 2, "start_level": 1, "end_level": 4, "cantrip_only": true, "from": "_dnd5e:spell_lists.warlock"},
        {"known": 3, "start_level": 4, "end_level": 10, "cantrip_only": true, "from": "_dnd5e:spell_lists.warlock"},
        {"known": 3, "start_level": 10, "cantrip_only": true, "from": "_dnd5e:spell_lists.warlock"}
    ]
}
